kind: pipeline
name: default
workspace:
    base: /go
    path: src/github.com/fanux/sealbot

# go mod vender
#environment:
#    GO111MODULE: on

steps:
- name: patch
  image: plugins/github-release

- name: build
  image: plugins/github-release

- name: publish
  image: plugins/github-release
  settings:
    api_key:
        from_secret: git-release-token
    files: sealbot
    title: ${DRONE_TAG}
    note: Note.md
